### ISSUE TITLE
Engineering: migrate the PopupUI to modern frontend framework

### ISSUE THREAD

**Issue by X140Yu** [ansh/jiffyreader.com#112]
As the project grows, popup UI is becoming more and more difficult to manipulate by Vanilla JavaScript, we can migrate the popup to a modern frontend like React

**Comment by jhonalino** [comment]
+1 on solidJS

**Comment by asieduernest12** [comment]
@X140Yu i think i would also pick react since it is familiar and probably most people have worked with it more compared to solid.
We also have to abstract or wrap the logic for setting up listeners, sending and responding to messages. presently its a lot of code to do either of these things.

**Comment by ansh** [comment]
I am ok with React, Preact, or Solid.

**Comment by asieduernest12** [comment]
@ansh I see your point too on not having a library. But we'll probably might have to if more complications come in to play but yeah the ui is simple so far.

We do have to update some of the wording to make it easier to understand on the ui. I'll make a draft or in a day or two on that anx you'll see.

**Comment by ansh** [comment]
@asieduernest12 I agree. I am eager to see your PR.

Also I wanted to add that the code might become more complicated with a framework since all the hard stuff about this extension is dealing with the edge cases, setting up listeners, etc., not the UI (which is just a few buttons and sliders). 

One of the reasons why I think this project is the most successful open-source implementation of BR is because it is so simple and easy for anyone to contribute. I literally made the first version in 15 minutes and people just started adding onto it! It was miraculous! The power of OSS! 

Adding a framework will simply dilute the base of potential devs that can contribute to this project and may make it more complicated for even the current devs to contribute.

**Comment by asieduernest12** [comment]
https://github.com/asieduernest12/jiffyreader.com/releases/tag/1.0.8.1204-development
