### ISSUE TITLE
Jiffy reader disables MacOS Force Click dictionary look up

### ISSUE THREAD

**Issue by faurehu** [ansh/jiffyreader.com#149]
On MacOS, using Force Click can be used to look up the definition of words. This is no longer working when Jiffy Reader is enabled.

**Comment by asieduernest12** [comment]
Thanks for reporting. Will see we can figure out the cause

**Comment by asieduernest12** [comment]
Sorry Faurehu how bionic reading works means force press will not work any more to select the complete word since it is now broken up into a set of character section/fragments which are bolded based on your fixation strength preference.

Solution.
Presently you can select the whole word manually before right clicking to lookup the definition.

**Comment by faurehu** [comment]
Ah well, I had to ask.

Thank you for having a look and thank you for maintaining this extension.
