### ISSUE TITLE
[BUG] Coloring "wrong"

### ISSUE THREAD

**Issue by ckruegerkpmg** [ansh/jiffyreader.com#154]
Hi,

the coloring idea is implemented "wrong".

The idea of beeline reader
https://github.com/ansh/jiffyreader.com/issues/56
 for the colors is not having sacades encoded in the colors but making sure that it's not easy to slip to the wrong line.
In Jiffy reader in line A and line B two word at the same horizontal position having the same color. The idea is that they have a different color.

greetings
Carsten

**Comment by asieduernest12** [comment]
@ckruegerkpmg thank you for noticing. This is not a bug. Our coloring implementation is inspired by beeline and not meant to be an exact implementation of the beeline coloring implementation.

If you want this specific feature then please open a feature request for it and hopefully a generous soul implements it and submit a pull request so that the implementation can be added to the project.
Cheers
