### ISSUE TITLE
[BUG] On Grammarly.com when you select a document it wipes the entire note.

### ISSUE THREAD

**Issue by carlanwray** [ansh/jiffyreader.com#156]
When using the editor on Grammarly.com when you open a document it wipes the entire note with no way to recover the lost information. (more of an issue of not having any history function)

Not hard to reproduce on Windows using Chrome. Go to grammarly.com, click an existing note and watch it all vanish.

Screen recording of issue:

https://somup.com/c3itDruyZq

**Comment by asieduernest12** [comment]
@carlanwray Terribly sorry about your encounter with this bug first reported #139 

a fix will be pushed promptly to fix this for you

It happens when a website has a custom data entry element which we are not able to detect because sometimes people build custom implementations for their specific needs

**Comment by asieduernest12** [comment]
Note if your data disappears while jiffy reader is on, turn it off and hit `ctrl +z` which worked while testing.
It is not a guaranteed solution.

**Comment by asieduernest12** [comment]
@carlanwray a fix has releases with version 1.0.8.1300. You can download the release now to get the fix or check either chrome or firefox stores in the next few hours for the newest update with version number referenced prior.
