### ISSUE TITLE
[BUG] updates trigger new browser tab to repo faq link

### ISSUE THREAD

**Issue by asrvd** [ansh/jiffyreader.com#158]
**Describe the bug**
Just as the title says, the extension forcibly opens the repo occasionally while browsing, I'm pretty sure this isn't a bug and maybe it's a way to make people come to know about the repo and star it? idk but it's annoying as hell, this actually made me remove the star which I had already done before even downloading the extension 👍🏼 

**To Reproduce**
browse.

**Expected behavior**
the extension shouldn't open any random site without my permission.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.41.100

**Comment by asieduernest12** [comment]
Sorry about that.

The current feature is meant to open the faq section of the github homepage when the application is first installed.

Unfortunately the feature is also being triggered on subsequent updates and we also notice this too as it spikes our metrics.

Ideally we only want to show/open the faq page only for new first installs because that is a better experience.

**Comment by asrvd** [comment]
I see, there should be some fix to it definitely

**Comment by asieduernest12** [comment]
> I see, there should be some fix to it definitely

We are actively looking into a good fix that has a better experience for both new users and current users

**Comment by asieduernest12** [comment]
@asrvd 1.0.9.1001 should have updated silently for you now without opening a new tab.

Cheers
