### ISSUE TITLE
Edge (Dev Channel) extension warning and default disable

### ISSUE THREAD

**Issue by CodeCharm** [ansh/jiffyreader.com#169]
Recently, Edge (on the Dev Channel) began warning me that the Jiffy Reader extension is disabled because it requires a permission that I hadn't granted it when I installed it: Display notifications

![image](https://user-images.githubusercontent.com/719997/183150764-01bd4cfc-ca49-4d94-9ed4-2614c984f2ed.png)

I'm really unclear why this is a required permission. I can't think of a valid reason. It has the feeling like it's required because that's how the Jiffy Reader extension is going to do random advertisements (spam) by way of displaying notifications. I'm not saying that's what I think it will do -- it's just a UX smell.

What am I missing?

**Comment by asieduernest12** [comment]
I believe they browsers are doing that because the permissions have changed.
Presently we are showing you a notification after installation/updates, that contains basic tips like telling you to pin the extension and also on chromium based browsers it shows you buttons to get to the faq and jiffyreader.com

It is the solution to previously rather opening the github page forcefully for all users on new updates or installations which was a terriblee experience. The notification can be dsimissed if a user has no relevance for it and it does not get in their way.

**Comment by asieduernest12** [comment]
@CodeCharm  how would you go about dealing with such a problem where 
**Go**al: show little tips and if possible actionable click buttons when the application is install for the firstime or on subsequent updates.
**pre**vious **imple**mentation: **wo**uld just open a new tab and direct to this github repo link.
**curr**ent **imple**mentation: use a notification element to show tips and action buttons that can be clicked to open a new tab to this repo and the notification is also dismissable if the user has no need for it

**Comment by CodeCharm** [comment]
@asieduernest12 I'm not so sure your first approach was a terrible approach. I would do that, except that I would use a different page to display for the first-time experience. I find that many extensions do show a web page when they are enabled for the first time, but they are typically designed just to be either "Welcome" help pages or possibly account sign-in pages. I have Edge (Chromium) installed on many devices, and with several profiles, and I have to re-install Edge several times a year (nature of my work), so it's quite normal to see several pages opened by extensions as the profile sync brings in extensions that are part of my profile. After I've seen the page for the first time, I know and expect it to show again, and it's easy to ignore and dismiss them, knowing they are not going to get re-shown until I re-install Edge or make a change to my profile and sync it, etc.

Because you have a public repository, you could use free GitHub Pages to show a much more user-friendly page when the extension is first enabled. I would _not_ make the Settings page for the extension as that first-time page, because your extension has a lot of settings, and that could be overwhelming for the new user.

When you require notification permissions, there's no way I can determine whether you will actually only show the notification just once after first-install on a new browser profile, or whether you'll show notifications again and again.

The notification approach is likely to continue to be problematic. The automatically-disabled-unconsented-permissions property of the Dev channel of Edge is very likely to get rolled out to the main public (GA) channel soon. It's possible, though I can't be sure) that Chrome also might get a similar outcome someday. Generally, if all that happens (and it seems likely that it will), the extension will be blocked by default unless the user consents to the permissions when it's first installed. 

I believe many users will not understand why this extension needs permission to display notifications, because it's not clear what the need or purpose of notifications for this particular extension would be. Experienced users like me might refuse to grant those permissions, because my (our) experience with required permissions like this are that they support (unsolicited) advertisements, AKA "spamware". Naive users will just consent, which puts them at risk for spamware extensions.

And finally, it's terribly easy to overlook, ignore, or inadvertently dismiss a notification. If you have a ready-to-go Welcome page (perhaps in GitHub Pages), you can easily supply a link back to that on the extension popup panel.

**Comment by asieduernest12** [comment]
@CodeCharm i get your point now.
So I also thought just redirecting to your repo link is simple since we have some basic intro  and explanations to help new users. Like killing many birds with as few stones as possible.
We really got review thanking us for showing the faq page and someone else opened a ticket complaining that their browser suddenly opens a new pag to the repo.

For now I know that random open behaviour actually happens when an update occurs.

I was thinking the notification is cleaner and let's me update the message for new updates.

I guess I take out the notification and instead revert to the old approach and also add a welcome section to the Readme for new users. That way old users recognize what's happening and can gracefully ignore the help/welcome page and simply close it. While the same page affords new users with a basic intro on how to find basic usage info if they get confused.
