### ISSUE TITLE
Doesn't work correctly on google drive nor any online pdf readers

### ISSUE THREAD

**Issue by Sininejuust** [ansh/jiffyreader.com#20]
I was planning on using it to help me better read school notes on google docs, but it only transforms the name of the document and the drop-down lists, but not the main body of the text :(

**Comment by tzazixten** [comment]
Just made an account to say this. I would love support for pdf files as well !

**Comment by ansh** [comment]
Unfortunately getting it to work on Google Docs and on PDFs is extremely difficult (via a chrome extension, easy if it were a separate website)

**Comment by tzazixten** [comment]
Ah damn. Fair enough. But I think there would be lots of interest for a tool like this to be able to read pdf files, as that is the format 90% of difficult texts I read is in. If some people are up for the task, it would be highly appreciated:)

**Comment by tzazixten** [comment]
I just tried converting 5 different pdf files, and it doesn't really work. Only on italics, and other small bits, for some reason. I think it is because of the way the text is written in pdf (converted to html), that must be different to normal html (obviously, I guess, I'm not really a programmer). Perhaps to avoid misuse of copyrighted books or something.

When you F12 and inspect element it looks like this in my pdf converted to html. I hope it helps somebody:
![image](https://user-images.githubusercontent.com/106098817/170126528-055436b8-537a-40e1-a9bc-fe56c73982dd.png)
![image](https://user-images.githubusercontent.com/106098817/170126710-f141ebce-be32-4de2-b119-3b7e545c76fc.png)

And another one like this:
![image](https://user-images.githubusercontent.com/106098817/170127088-0f9eab8b-95c4-4b56-a64d-7f8eb366924b.png)
![image](https://user-images.githubusercontent.com/106098817/170127192-4b8d4018-fc20-4d63-9893-85e5ecc920da.png)

And here it works for a small part of the text, but it creates weird spaces in the middle of the words too
![image](https://user-images.githubusercontent.com/106098817/170127800-ce28eeca-bd77-4671-8823-e5b3660fc6f8.png)
![image](https://user-images.githubusercontent.com/106098817/170127973-fa1d9534-0944-4dc2-bd48-8a5704d3e6cb.png)

I hope this is useful info, for the right person.

**Comment by reaseno** [comment]
I converted my PDF to HTML and it only works when I put it on a web server. Why doesn't it work with a local HTML file?

**Comment by rahilwazir** [comment]
> I converted my PDF to HTML and it only works when I put it on a web server. Why doesn't it work with a local HTML file?

Because the extension only [works for the `http(s)://` protocol](https://github.com/ansh/jiffyreader.com/blob/master/src/manifest.json#L24). I think adding a `file://` should do the trick if I'm not mistaken.

**Comment by reaseno** [comment]
Doesn't sound like it would be a complicated fix 🤔

**Comment by ansh** [comment]
If you think so you can submit a PR! Thanks :)

**Comment by asieduernest12** [comment]
@reaseno try the extension with your local files again.
Can you share the process you took to convert your pdf?

**Comment by reaseno** [comment]
I used this for conversion:
https://cloudconvert.com

**Comment by asieduernest12** [comment]
> I used this for conversion: https://cloudconvert.com

i was able to convert a pdf to epub
uploaded the epub to google play books
able to read it with jiffyreader

i am guessing this all works provided the pdf version is storing actual text because there are many versions of the pdf specification.

Some specs support text while others are intented for storing images in varying resolutions.
If the pdf is in the image specification then probably this will not work

**Comment by reaseno** [comment]
@asieduernest12 
I tried again with a local HTML file. Now the extension says:
**Tabs without a url may not work properly
Reload the tab with valid url and try again**.

Then I enabled "Allow access to file URLs" in the browser for the extension. After that, jiffyreader worked with that local file. I had already tried this on June 27, where it still did not work. If there was a fix, thank you very much.

**Comment by asieduernest12** [comment]
@reaseno super interesting so now it seems we have solved the issues with not being able to read pdfs.
I totally forgot about enabling the extension to access file url when i was testing.

so you can use cloudconvert.com to convert a pdf to html and view it right in the browser. With the second option being converting to an epub and uploading to google play which means you can technically read it anywhere from any other browser.

a nice feature then would be `read a pdf` which would handle the upload and conversion seemlessly and then showing the result as jiffied text.

**Comment by asieduernest12** [comment]
> @asieduernest12 I tried again with a local HTML file. Now the extension says: **Tabs without a url may not work properly Reload the tab with valid url and try again**.
> 
> Then I enabled "Allow access to file URLs" in the browser for the extension. After that, jiffyreader worked with that local file. I had already tried this on June 27, where it still did not work. If there was a fix, thank you very much.
![TheUniverseTimAndEricMindBlownGIF](https://user-images.githubusercontent.com/20851930/183372008-d23d0bf0-eb12-492e-b3a9-5c1300b65022.gif)
![PeaceOutIceAgeGIF](https://user-images.githubusercontent.com/20851930/183372043-565b6819-1fcd-46b8-9fe6-7ec984d7050a.gif)
