### ISSUE TITLE
Can we optimize implement?

### ISSUE THREAD

**Issue by Siltal** [ansh/jiffyreader.com#200]
![inject div in root](https://user-images.githubusercontent.com/35952127/207800564-1d9b72b4-c067-42f8-a7cd-993320897884.png)
![when I disable the extentsion](https://user-images.githubusercontent.com/35952127/207800714-17c922ab-1b1d-4260-9955-d6771bf85e5d.png)

**Comment by ansh** [comment]
@Siltal Please give more details. What do these screenshot mean?

**Comment by Siltal** [comment]
当我启用这个扩展时，它会使页面增加一个div

**Comment by asieduernest12** [comment]
@Siltal technically we jiffyreader adds many new lements onto a page and not just one div. This is required to provide the core functionality. Please explain what the issue is.
What happens to your page when an extra div is added. 
Things to consider, can you adapt css to make the issue go away
or can you use js to make the issue go away. 

Side note if you are actively developing a website/app then turn off jiffyreader or use the options to disable it for localhost and 127.0.0.1
