### ISSUE TITLE
[BUG] Visited links maintain the blue font color of a nonvisited links, screenshots in comments

### ISSUE THREAD

**Issue by ThinkSalat** [ansh/jiffyreader.com#207]
**Describe the bug**
links have an affordance which tells you whether you've visited or not. this is standard across browsers most of the time.
typically, a blue link hasn't been visited and a purple link has. It's rather arbitrary but it's understood by anyone who has used a browser before.

Many websites will have different CSS that describes links' visited and unvisited state.

Here's what google search looks like
![image](https://user-images.githubusercontent.com/31082405/219083929-56aa8093-25be-4796-999d-cf8054f33cf1.png)

Here's how it should look ideally: 
![image](https://user-images.githubusercontent.com/31082405/219084939-d15192bb-03db-4eee-b87e-e292f2731d20.png)

Recommendation:

Find the most specific css code that alters the visited link color or style, and apply that style when applying the bionic text style.

The culprit appears to be the color applied in the following style injection:
![image](https://user-images.githubusercontent.com/31082405/219085219-252a462d-3381-4f6a-968e-1127738fa7ec.png)

As you can see, all I needed to do was disabled the   `color: var(--saccadesColor);` style attribute to address the issue.

**Comment by asieduernest12** [comment]
@ThinkSalat I can confirm our code is not impacting the behaviour of browser links changing color when visited. You can confirm the behaviour by opening a link in a new tab and you will be able to see the link change color even when jiffyreader is turned on.

Let us know if anything else bothers you and we will be happy to investigate.
Sorry you had to go digging in that css pile ✌🏾

**Comment by ThinkSalat** [comment]
Yes, a visited link changing color is not the issue! That's expected behavior. The issue is that when the style is injected onto a link that's been visited, it allows the `color: var(--saccadesColor); style. However saccasdesColor is being generated, it should be taking into account whether a link is visited. Should be easy enough to just select for the closest `color` being specified in the css

**Comment by asieduernest12** [comment]
@ThinkSalat i am not sure i understand your problem, from the title of the issue you state that unvisited links should have color x ,
then change to some color y when they have been visited. This has been validated as being the manifested behaviour,

It is not that easy to look up the css because we dont lookup anyones css to do anything, all the styling magic happens by adding flags to the css on the body element with different configuration values, No javascript is involved with regards to actually styling the effects, Your proposed simple solution wont work because there is no js running though setting different css values on things.

Feel free to send in a pull request or proof of conccept of how you would solve this, I would be more than happy to look over it . A good place to look is the file src/styles/ContentSyles.scss


Let me know how it goes.
![PeaceGIF](https://user-images.githubusercontent.com/20851930/220116647-4dc713fd-70e0-483a-b02b-b88109ed0e35.gif)

**Comment by asieduernest12** [comment]
@ThinkSalat modularizing the css through the scss and adding another mechanism to conditionally injected while making sure that it has not been injected again and making that also work with the monkey scripts for people that want just the functionality without the packaged extension is something we will leave to a pull request from a kind volunteer.

**Comment by ThinkSalat** [comment]
It's really just a matter of when the saccadesColor is being applied to open links and making sure it follows those rules. I've done  a cursory glance through the codebase and can verify that this is not out of the scope of the javascript running in the project. That said I'd stopped using the project myself, as I've seen no benefit from "bionic reading" Though I'll leave my glowing google review up:) Peace out
