### ISSUE TITLE
[FEATURE] Option to automatically disable extension when the user clicks in an <input/>

### ISSUE THREAD

**Issue by snoblenet** [ansh/jiffyreader.com#218]
**Is your feature request related to a problem? Please describe.**

The bugs I've seen mostly relate to text input.

But on those sites, I'd still like to read in binary mode. I just want binary mode to be disabled if/when it poses a problem with input.

**Describe the solution you'd like**

On every <input/>, there is a listener that disables binary mode while the user inputs data.

**Additional context**

Commenting on the Jira and Confluence is an example of where this would be valuable.

**Comment by asieduernest12** [comment]
@snoblenet great suggestion which has been an issue #138  that is headache dealing with since some websites are completely implementing custom input fields. This has to be investigated further probably with your help over zoom to see what happens in Jira and confluence. 

Send an email to jiffyreader007@gmail.com and lets see if we can work out something. Fingers crossed.
![PleaseCatGIF](https://user-images.githubusercontent.com/20851930/225776180-d20ca80f-758a-4fb6-9d84-e208892b0b7a.gif)
