### ISSUE TITLE
[BUG] The Bold-500 doesn't seem to work for me, it looks like the standard 600 setting

### ISSUE THREAD

**Issue by github1328** [ansh/jiffyreader.com#229]
**Describe the bug**
The standard saccades styles Bold-600 setting makes the effect stand out too much in my opinion, but 400 is too subtle. So the 500 setting is probably what I want, but I doesn't seem to work properly. It looks exactly like the standard 600 setting. So I can't get this in-between look I'm looking for.
I just noticed though that it does do something: code blocks here on github look like the 400 setting for both 400 and 500, while all the normal text looks like 600 for both 500 and 600.

**To Reproduce**
Set saccades styles to Bold-500

**Expected behavior**
A boldness look in between 400 and 600...

**Screenshots**
![bold400](https://user-images.githubusercontent.com/132098201/235457752-31c59e27-e200-4e5f-b089-6e6b0d66055b.png)

![bold500](https://user-images.githubusercontent.com/132098201/235457753-60f82ba2-4c73-4a33-81d2-7d3baa0161a4.png)

![bold600](https://user-images.githubusercontent.com/132098201/235457755-d55895dc-e1ba-47a6-9f14-7b42aa3a5d47.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome, edge]
 - Version [112, 112]
 - Extension version [1.0.9.1010]

Love the extension otherwise, thank you for your work!

**Comment by asieduernest12** [comment]
@github1328 thank you for reporting this however this the boldness settings changes in little increments.
That means two adjacent settings may be perceived by your eyes or sensory medium as class.

The great thing is you found the option of choosing a different setting that works for you which is the right way to go. 

We'll close this issue now. Enjoy reading

**Comment by github1328** [comment]
> @github1328 thank you for reporting this however this the boldness settings changes in little increments. That means two adjacent settings may be perceived by your eyes or sensory medium as class.

Thank you for your reply. I'm sure what you are saying is true, but something other than my perception is definitely off. I've compared lots of screenshots. The effect is very inconsistent across platforms, especially the settings I was talking about. On some browsers/settings/... it's the way I posted, on others it's basically the opposite, next one it's unclear, very rarely it looks like I'd imagine, etc. 

If it's not a bug and I'm not delusional it probably depends on some specific settings/circumstances. Or the numbers are correct but in practice (or at least on my end) maybe the numbers don't correspond to the perceived value (even then, very inconsistent), so maybe it would make sense to adjust the numbers to better achieve a perceived halfway mark between 400 and 600. 

Can it have to do with display DPI settings? Or changes in fonts? I'm just so confused why the 500 always looks almost identical like a 400 or a 600 but never like something in between... If it's a problem on my end, fine. If it's the same for everyone I think everyone expects a setting of 5 between 4 and 6 to look like an in between setting, and sometimes numbers lie.

>The great thing is you found the option of choosing a different setting that works for you which is the right way to go.

Sadly I can't get it to work in a way that perfectly works for me because what I would want is the setting between 400 and 600 that is either too close too 600 or to 400 but never the assumed midway point.

Please don't take this as critical or anything, I'm very happy with your work and thank you for it. I just want to make sure this is not an easily fixable problem that many people are annoyed by. If this is not something to investigate further that's absolutely fine, it very well could be an issue on my end, I'm just skeptical.

Thank you and take care.

**Comment by asieduernest12** [comment]
@github1328 I appreciate the passion to be so thorough with your thoughts and interest to convey the problem and break it down so delicately.

The problem seems to be an issue specifically with fonts weights is that the given font on a site will only show the font weights values that its authors have included. 
According to the font specification , unless i am wrong; the font weights that a given font is capable of supporting is within the range of 100 - 900.
Hover it seems most fonts only come with a few noticable values within the range. I don't know how much effort is involved in making fonts of varying wiehgts as I have never designed fonts because i assume they have to deal with edge cases to make sure a font is pleasant across a wide range of wieght values. 
This issue probably will exist on every single website ever made as long as their font weight options don't cover every range between 100 and 900.
It also seems there is a way that browsers pick an alternative font weight if the desired weight is not found, the algorithm seems to pick the next closest weight available which may be higher or lower.

One option to actually resolve this is to include our on font which has covers a wider spectrum in the font weight range which would allow you or anyone else to have a finer control of their fonts.

You can read more on the font weight here [here](https://www.scaler.com/topics/font-weight-css/)

![image](https://github.com/ansh/jiffyreader.com/assets/20851930/a1b9b318-eff2-4bd3-9f21-64483f20e21b)
