### ISSUE TITLE
[BUG] Frequently speedtest to cost network traffic

### ISSUE THREAD

**Issue by h3ar7dump** [ansh/jiffyreader.com#298]
**Describe the bug**
the entension will frequently accessing speed.cloudflare.com to do speed test, which cost to much network traffic.

**To Reproduce**
just open the extension and inspect popup.

<img width="1001" alt="9764ddfc8928d6f5fc2b379151cf117" src="https://github.com/user-attachments/assets/bb5d312c-901e-471d-8efa-3795bf61ba47">

<img width="1012" alt="030a5a091d91bee347466b2d7fb41b1" src="https://github.com/user-attachments/assets/37efa804-b06f-4c1e-bba6-56f475ab584f">

**Desktop (please complete the following information):**
 - OS:  windows11 23H2
 - Browser [chrome]
 - Version [127.0.6533.100]
 - Extension version [1.1.7]

**Additional context**
I tried to locate the source code, but didn't to find out.
Only found in pnpm-lock.yml
<img width="1023" alt="f19474f139652a9f7bd3657c486c87f" src="https://github.com/user-attachments/assets/8ba9c759-755f-4ecb-81cc-c2d72e0adb9a">

**Comment by mellowtel** [comment]
Hey @h3ar7dump, it's Arslan from [Mellowtel.dev](https://www.mellowtel.dev/about-mellowtel/)!

We're building an [open-source library](https://github.com/mellowtel-inc/mellowtel-js) to help extension developers monetize their free plugins thanks to bandwidth sharing. The speed test you noticed is triggered here in this [function](https://github.com/mellowtel-inc/mellowtel-js/blob/6c5218a3fe5c0bdc51223303b65a1c8ca6cc60d1/src/utils/measure-connection-speed.ts#L8). Unfortunately there was a bug in this version and the speed test is run on every page load  instead of every 8 hours and that is what is consuming network traffic. This will be fixed very soon.

Still, we understand not everyone may be able or willing to share their network bandwidth, so feel free to opt-out from the JiffyReader popup. If you opt out, the speed test won't be run anymore.

**Steps to opt out**

1. Open the JiffyReader popup
2. On the right side of "Report issues" in the green footer there is a "Mellowtel" link
3. Clicking the link opens a small popup window
4. There is a white button with the text "Opt out". Click on it to opt out

Thanks for understanding and let me know if you want other clarifications,
Arslan

**Comment by mellowtel** [comment]
I opened this PR: https://github.com/ansh/jiffyreader.com/pull/299 which fixes all the issues related to high network consumption. Hopefully we'll be able to merge and deploy in prod quickly. Sorry for the issues caused
