### ISSUE TITLE
Attempted to use on a few common sites, most only work conditionally

### ISSUE THREAD

**Issue by itsNilson** [ansh/jiffyreader.com#8]
Not an overly techy user apologies in advance, made an account just to watch the progress of this project :)

Downloaded the extension, installed using instructions from an earlier logged issue. Tested it on some common websites I use, currently using chrome Version 101.0.4951.67 (Official Build) (64-bit), here's a round up from 15 minutes of use:

Did not work on any part of the page as far as I could see (which arguably is the main goal for an extension like this, particularly with the claim that it works on any website):
- Facebook
- Youtube

Worked conditionally (Converted only main bodies of text, removing and in-text hyperlinks).
- Wikipedia
- DNDBeyond
- Old Reddit
- New Reddit
- GitHub 
- GMail
- Amazon (not homepage - individual listings of items)
- FinalFantasyXIV store - only the copyright information at the very bottom of the page

Overall really impressed with the text that it was able to convert, very excited to see the progress with this :)

**Comment by majulahsingapuri** [comment]
Adding on to this, for Wikipedia, it converts $\LaTeX$ to the raw code.

Normal Text
![Screenshot 2022-05-24 at 9 54 22 AM](https://user-images.githubusercontent.com/13448687/169933091-ea037982-e7c0-4b47-a498-ec17f4e54a23.png)

With Bionic Reading
![Screenshot 2022-05-24 at 9 57 06 AM](https://user-images.githubusercontent.com/13448687/169933078-d8db0c88-5978-4cc9-b697-5d97ce5ea023.png)

**Comment by MonsalvoGeoffrey** [comment]
When it comes to GitHub, I've noticed on my own project that links won't actually always reload the entire page, but only the part of it that changed, and that doesn't reload the content script of add-ons.

Because of that, this add-on seems to fails on elements that have changed from one page to another, but otherwise work fine after a refresh. I haven't figured a way around it myself, but I hope that can help, as I assume other websites probably have a similar issue

**Comment by asieduernest12** [comment]
happy to report this as resolved

![Screenshot from 2022-06-04 02-25-17](https://user-images.githubusercontent.com/20851930/171987455-0bf437b0-7ace-482d-b80b-d93300254b24.png)
