### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by htadashi** [ansh/jiffyreader.com#96]
The XSS vulnerability reported by @augustozanellato in https://github.com/ahrm/chrome-fastread/issues/10#issuecomment-1140411767 is also present on Jiffy reader.

**Comment by X140Yu** [comment]
The Chrome Store version does have this issue, but I tried with the latest master on the poc, and the issue has been fixed, need to furder confirm

**Comment by Explosion-Scratch** [comment]
> I have provided a hackish solution in that discussion, which uses a simple htmlescaper to prevent basic XSS. See more [here](https://github.com/ahrm/chrome-fastread/issues/10#issuecomment-1140411767). Let me know if anyone has a better solution!

Hackish would be making a function that sets innertext of a created element then gets its HTML, regex is not hackish

**Comment by asieduernest12** [comment]
Resources
https://gomakethings.com/preventing-cross-site-scripting-attacks-when-using-innerhtml-in-vanilla-javascript/

**Comment by HuiiBuh** [comment]
I honestly am not even sure if there is a potential for a xss attack.
Something like `<script>alert("asdf")script>` always gets broken up and ends up like this.
![image](https://user-images.githubusercontent.com/46561026/179695890-37d32ffc-fda1-435c-bf3b-a5dbffd9c163.png)

In addition to that this regex `\p{L}` searches for letters. 
https://github.com/ansh/jiffyreader.com/blob/a265fca2e59df35533fddc3103919886f144f532/src/ContentScript/documentParser.js#L36
And as far as I know there is no way to compose an xss attack with only special characters (But I might be wrong on this account) and not a single letter, because everything else (a mix of both) will be replaced with some custom `<br-bold>` elements in between.

**Comment by ansh** [comment]
Closing as not a concern at the moment.

Any proof of a genuine vulnerability will necessitate a re-opening of this issue.
